//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bank
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bills
    {
        public int Id { get; set; }
        public int ClientID { get; set; }
        public int BillNum { get; set; }
        public string InclusionDate { get; set; }
        public string InclusionDateEnd { get; set; }
        public double InclusionSum { get; set; }
        public double Percents { get; set; }
        public bool Capitalize { get; set; }
        public int Total { get; set; }
        public string StatusInclusion { get; set; }
    
        public virtual Clients Clients { get; set; }
    }
}
